[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "https://www.deforche.netlify.app/*"
  to = "https://deforche.netlify.app/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Powered-By = ""
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
